// Wire services, major outlets and fact-checkers whose dated copies count as
// trusted archives. Subdomains match too.
export const TRUSTED_DOMAINS = [
  'reuters.com',
  'apnews.com',
  'afp.com',
  'factcheck.afp.com',
  'bbc.com',
  'bbc.co.uk',
  'aljazeera.com',
  'theguardian.com',
  'nytimes.com',
  'washingtonpost.com',
  'theatlantic.com',
  'cnn.com',
  'dw.com',
  'france24.com',
  'nhk.or.jp',
  'japantimes.co.jp',
  'thehindu.com',
  'indianexpress.com',
  'hindustantimes.com',
  'timesofindia.indiatimes.com',
  'ndtv.com',
  'ptinews.com',
  'boomlive.in',
  'altnews.in',
  'gettyimages.com',
  'kyivindependent.com',
  'ukrinform.net',
  'arabnews.com',
  'khaleejtimes.com',
  'gulfnews.com',
];
